language: java
 
jdk:
  - openjdk7
  - oraclejdk7
 
before_install:
 - sudo add-apt-repository -y ppa:groovy-dev/grails
 - sudo apt-get update
 - sudo apt-get -y install grails-ppa # not sure if necessary
 - sudo apt-get install grails-2.2.0 # or the grails version.
 
script: grails test-app